# ============================================
# Docker Compose — Environnement de DÉVELOPPEMENT
# ============================================
# Lance 2 services :
#   - db  : base MySQL 8
#   - web : application Django
# ============================================
services:
    db:
      image: mysql:8.0
      container_name: library_mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: library_db
        MYSQL_USER: library_user
        MYSQL_PASSWORD: library_password
        MYSQL_ROOT_PASSWORD: root_password
      ports:
        - "3310:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      healthcheck:
        test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-proot_password"]
        interval: 5s
        timeout : 5s
        retries: 10
    web:
      build:
        context: .
        dockerfile: docker/Dockerfile
      container_name: library_web
      restart: unless-stopped
      command: python  manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy
volumes:
  mysql_data:
