# ============================================
# Dockerfile de DÉVELOPPEMENT
# ============================================
# Ce Dockerfile est utilisé pour le développement local.
# Il installe les dépendances de dev (tests, lint, etc.)
# ============================================

FROM python:3.12-slim

# Empêche Python d'écrire des .pyc et active les logs en temps réel
ENV  PYTHONDONTWRITEBYTECODE=1 \
     PYTHONUNBUFFERED=1 \
     PIP_NO_CACHE_DIR=1 \
     PIP_DISABLE_PIP_VERSION_CHECK=1


# Dépendances système nécessaires à mysqlclient
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Répertoire de travail
WORKDIR /app

# Installation des dépendances Python (d'abord pour profiter du cache Docker)
COPY requirements/ /app/requirements/
RUN pip install --upgrade pip && \
    pip install -r /app/requirements/development.txt

# Le code sera monté via volume dans docker-compose (pas copié)
# cela permet le hoat-reload en developpement
